POST http://localhost:3000/login
Content-Type: application/json

{
    "uname": "jakub",
    "password": "123"
}
###

GET http://localhost:3000/6465fe724b087ad1e5ac61d8
Content-Type: application/json

{
    "jwt" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY1ZmU3MjRiMDg3YWQxZTVhYzYxZDgiLCJ1bmFtZSI6Impha3ViIiwicGFzc3dvcmQiOiIkMmEkMTIkbDhSQzkwUnJoU3cyS09QZW9VZ0w4T2NWZG83bmUvN2tpWjFBYkpjaEVPa3ZiZ3JOUlAwUVMiLCJwZXJtcyI6WyJzdG9yeUNoYW5uZWwiXSwiX192IjowLCJpYXQiOjE2ODQ0MzUyNDYsImV4cCI6MTY4NDQzNjE0Nn0.ngVFuMoL4M1sdFo43bUgZFyiufAIu5E7B6Se4f2ES4c"
}


###
GET http://localhost:3000/6465fe724b087ad1e5ac61d8/storyChannel
Content-Type: application/json

{
    "jwt" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY1ZmU3MjRiMDg3YWQxZTVhYzYxZDgiLCJ1bmFtZSI6Impha3ViIiwicGFzc3dvcmQiOiIkMmEkMTIkbDhSQzkwUnJoU3cyS09QZW9VZ0w4T2NWZG83bmUvN2tpWjFBYkpjaEVPa3ZiZ3JOUlAwUVMiLCJwZXJtcyI6WyJzdG9yeUNoYW5uZWwiXSwiX192IjowLCJpYXQiOjE2ODQ0MDgyOTQsImV4cCI6MTY4NDQwOTE5NH0.byHEIXJr-S8woe44a73V_V9tDCPxTheZYHfI_GoJh0I"
}

###

POST http://localhost:3000/6465fe724b087ad1e5ac61d8/storyChannel/new
Content-Type: application/json

{
    "jwt" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY1ZmU3MjRiMDg3YWQxZTVhYzYxZDgiLCJ1bmFtZSI6Impha3ViIiwicGFzc3dvcmQiOiIkMmEkMTIkbDhSQzkwUnJoU3cyS09QZW9VZ0w4T2NWZG83bmUvN2tpWjFBYkpjaEVPa3ZiZ3JOUlAwUVMiLCJwZXJtcyI6WyJzdG9yeUNoYW5uZWwiXSwiX192IjowLCJpYXQiOjE2ODQ0MDgyOTQsImV4cCI6MTY4NDQwOTE5NH0.byHEIXJr-S8woe44a73V_V9tDCPxTheZYHfI_GoJh0I",
    "title" : "Cool Monks"
}

###
GET http://localhost:3000/6465fe724b087ad1e5ac61d8/storyChannel/646608109f4dcf370d4f7c3d
Content-Type: application/json

{
    "jwt" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY1ZmU3MjRiMDg3YWQxZTVhYzYxZDgiLCJ1bmFtZSI6Impha3ViIiwicGFzc3dvcmQiOiIkMmEkMTIkbDhSQzkwUnJoU3cyS09QZW9VZ0w4T2NWZG83bmUvN2tpWjFBYkpjaEVPa3ZiZ3JOUlAwUVMiLCJwZXJtcyI6WyJzdG9yeUNoYW5uZWwiXSwiX192IjowLCJpYXQiOjE2ODQ0MzY5NDksImV4cCI6MTY4NDQzNzg0OX0.FSjGTE9jOyiVARWUKuNQyMcUGA5qtp1B1LfeCYa8K24"
}

###
POST http://localhost:3000/6465fe724b087ad1e5ac61d8/storyChannel/646608109f4dcf370d4f7c3d/gpt
Content-Type: application/json

{
    "jwt" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDY1ZmU3MjRiMDg3YWQxZTVhYzYxZDgiLCJ1bmFtZSI6Impha3ViIiwicGFzc3dvcmQiOiIkMmEkMTIkbDhSQzkwUnJoU3cyS09QZW9VZ0w4T2NWZG83bmUvN2tpWjFBYkpjaEVPa3ZiZ3JOUlAwUVMiLCJwZXJtcyI6WyJzdG9yeUNoYW5uZWwiXSwiX192IjowLCJpYXQiOjE2ODQ0MzY5NDksImV4cCI6MTY4NDQzNzg0OX0.FSjGTE9jOyiVARWUKuNQyMcUGA5qtp1B1LfeCYa8K24"
}